services:
  showgeki2:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - WATCH_MODE=true
      - OPENAI_IMAGE_QUALITY_DEFAULT=medium
    env_file:
      - .env.local
    volumes:
      - ./scripts:/app/scripts
      - ./logs:/app/logs
      - ./output:/app/output
      - ./mulmocast-output:/app/mulmocast-cli/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    stdin_open: true
    tty: true